In [8]:
import numpy as np

a = np.random.randn(5)

print(a)

[ 2.66987095  0.04868928 -0.70693784 -1.45955221 -1.15911929]


In [9]:
print(a.shape)

(5,)


In [10]:
print(a.T)

[ 2.66987095  0.04868928 -0.70693784 -1.45955221 -1.15911929]


This shows us that a (the matrix) and a.transpose are the same.
Ultimately, you should not use data structures where the shape is (5,)—this is called a rank 1 array. 
Use  a column (5,1) or row (1,5) vector instead.

In [11]:
print(np.dot(a,a.T))

11.104192793440628


In [12]:
a = np.random.randn(5,2)
print(a)

[[ 1.29131043e+00  6.92696862e-01]
 [-3.97183732e-01  5.55692543e-01]
 [ 4.76241284e-04  5.59121578e-01]
 [ 8.08130072e-01 -6.72011669e-01]
 [-1.57775155e+00 -1.25140126e+00]]


In [13]:
print(a.T)

[[ 1.29131043e+00 -3.97183732e-01  4.76241284e-04  8.08130072e-01
  -1.57775155e+00]
 [ 6.92696862e-01  5.55692543e-01  5.59121578e-01 -6.72011669e-01
  -1.25140126e+00]]


In [14]:
print(np.dot(a,a.T))

[[ 2.14731157 -0.12796101  0.38791674  0.57804642 -2.90420875]
 [-0.12796101  0.46654912  0.31051054 -0.69440799 -0.0687371 ]
 [ 0.38791674  0.31051054  0.31261717 -0.37535136 -0.70043684]
 [ 0.57804642 -0.69440799 -0.37535136  1.1046739  -0.43407223]
 [-2.90420875 -0.0687371  -0.70043684 -0.43407223  4.05530505]]


That's better!